### ISSUE TITLE
Font family missing

### ISSUE THREAD

**Issue by TA-Hemanth** [Raiper34/ngx-simple-text-editor#20]
No option for change font family

**Comment by Raiper34** [comment]
Hi, 
you can use regular scss like
```scss
::ng-deep st-editor {
  font-family: "Gill Sans", sans-serif;
}
```
